export { default as Students } from './MainPage/Students/Students'
export { default as ModalJurnal } from './MainPage/ModalJurnal/ModalJurnal'
export { default as StudentsList } from './Teacher/StudentsList/StudentsList'
export { default as JournalStudent } from './Student/JournalStudent/JournalStudent'
export { default as Dekanat } from './MainPage/Dekanat/Dekanat'
export { default as SearchStudent } from './SearchStudent/SearchStudent'
export { default as Teacher } from './Teacher/Teacher/Teacher'
// export { default as } from ''
