export { default as Pencil } from './pencil.svg'
export { default as Square } from './square.svg'
export { default as Exit } from './bx_exit.svg'
export { default as Trash } from './trash.svg'
// export { default as  } from ''
